// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Jams_Debugger","status":true,"description":"Debugger that adds more metrics to the FPS window when you press f2.","parameters":{"enablePos":"true","posPage":"0","enableConsolePeek":"true","consolePeekPage":"1"}},
{"name":"Jams_Mapper","status":true,"description":"Mapper is a plugin that combines maps together and points to the new maps when the game is ran.// Describe your plugin","parameters":{"command      //name of a parameter you want the user to edit":"na    // set default value for the parameter"}}
];
